export const META = {
  url: "https://studio-nm.co.kr/",
  page_url: "https://studio-nm.co.kr/",
  metadataBase: new URL("https://studio-nm.co.kr/"),
  title: "스튜디오 낭만, 모든 것을 가능하게 하다.",
  description:
    "서비스기획, BX 디자인, 상세디자인, 광고 디자인, 명함 디자인, 웹 개발, 앱 개발, 웹앱개발, 유지보수, 서비스 운영, 지원 사업 컨설팅 등 다양한 서비스를 낭만에서 제공합니다.",
  keywords: [
    "서비스기획",
    "서비스개발",
    "디자인",
    "웹개발",
    "웹앱개발",
    "앱개발",
    "지원사업컨설팅",
    "청창사",
    "초창페",
    "장충대",
    "낭만",
    "낭만이 있는 곳",
    "낭만과 함께",
    "서비스 런칭",
    "컨설팅",
  ],
  icons: [
    {
      url: "/apple-icon-57x57.png",
      type: "image/png",
      sizes: "57x57",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-60x60.png",
      type: "image/png",
      sizes: "60x60",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-72x72.png",
      type: "image/png",
      sizes: "72x72",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-76x76.png",
      type: "image/png",
      sizes: "76x76",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-114x114.png",
      type: "image/png",
      sizes: "114x114",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-120x120.png",
      type: "image/png",
      sizes: "120x120",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-144x144.png",
      type: "image/png",
      sizes: "144x144",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-152x152.png",
      type: "image/png",
      sizes: "152x152",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-180x180.png",
      type: "image/png",
      sizes: "180x180",
      rel: "apple-touch-icon",
    },
    {
      url: "/android-icon-192x192.png",
      type: "image/png",
      sizes: "192x192",
      rel: "icon",
    },
    {
      url: "/favicon-32x32.png",
      type: "image/png",
      sizes: "32x32",
      rel: "icon",
    },
    {
      url: "/favicon-96x96.png",
      type: "image/png",
      sizes: "96x96",
      rel: "icon",
    },
    {
      url: "/favicon-16x16.png",
      type: "image/png",
      sizes: "16x16",
      rel: "icon",
    },
    {
      url: "/favicon.ico",
      type: "image/x-icon",
      sizes: "16x16",
      rel: "icon",
    },
  ],
  // manifest: "/manifest.json",
  twitter: {
    images: {
      url: "/twitter-image.jpg",
      width: 1200,
      height: 630,
      alt: "Studio Nangman Twitter Image - 서비스 기획, UXUI 디자인, 브랜딩, 앱 개발, 웹 개발, 앱웹개발, 유지보수, 서비스 운영, 지원 사업 컨설팅 등 다양한 서비스를 낭만에서 제공합니다.",
    },
    card: "summary_large_image",
    site: "@studioNM_co_kr",
    creator: "@studioNM_co_kr",
  },
  openGraph: {
    type: "website",
    locale: "ko_KR",
    url: "https://studio-nm.co.kr/",
    siteName: "스튜디오 낭만, 모든 것을 가능하게 하다.",
    title: "Studio NM - 스튜디오 낭만, 모든 것을 가능하게 하다.",
    description:
      "서비스기획, BX 디자인, 상세디자인, 광고 디자인, 명함 디자인, 웹 개발, 앱 개발, 웹앱개발, 유지보수, 서비스 운영, 지원 사업 컨설팅 등 다양한 서비스를 낭만에서 제공합니다.",
    images: {
      url: "/openGraph-image.jpg",
      alt: "Studio Nangman OpenGraph Image - 서비스 기획, UXUI 디자인, 브랜딩, 앱 개발, 웹 개발, 앱웹개발, 유지보수, 서비스 운영, 지원 사업 컨설팅 등 다양한 서비스를 낭만에서 제공합니다.",
      width: 1200,
      height: 630,
    },
  },
  other: {
    "theme-color": "#ffffff",
    "msapplication-TileColor": "#ffffff",
    "msapplication-TileImage": "/ms-icon-144x144.png",
    "msapplication-config": "/browserconfig.xml",
  },
  googleVerification: "xxx",
  naverVerification: "xxx",
};
