export const META = {
  url: "https://studio-nm.co.kr/",
  page_url: "https://studio-nm.co.kr/",
  metadataBase: new URL("https://studio-nm.co.kr/"),
  title: "아리사 | 부동산을 간편하고 안전하게 ",
  description: "아리사는 부동산 슈퍼앱입니다.",
  keywords: [
    "부동산, 부동산 슈퍼앱, 아리사, ARESA, 거래, 매매, 전세, 월세, 경매, 도전 자산, 부동산 이슈, 부동산 계산기, 아리사코리아",
  ],
  icons: [
    {
      url: "/apple-icon-57x57.png",
      type: "image/png",
      sizes: "57x57",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-60x60.png",
      type: "image/png",
      sizes: "60x60",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-72x72.png",
      type: "image/png",
      sizes: "72x72",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-76x76.png",
      type: "image/png",
      sizes: "76x76",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-114x114.png",
      type: "image/png",
      sizes: "114x114",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-120x120.png",
      type: "image/png",
      sizes: "120x120",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-144x144.png",
      type: "image/png",
      sizes: "144x144",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-152x152.png",
      type: "image/png",
      sizes: "152x152",
      rel: "apple-touch-icon",
    },
    {
      url: "/apple-icon-180x180.png",
      type: "image/png",
      sizes: "180x180",
      rel: "apple-touch-icon",
    },
    {
      url: "/android-icon-192x192.png",
      type: "image/png",
      sizes: "192x192",
      rel: "icon",
    },
    {
      url: "/favicon-32x32.png",
      type: "image/png",
      sizes: "32x32",
      rel: "icon",
    },
    {
      url: "/favicon-96x96.png",
      type: "image/png",
      sizes: "96x96",
      rel: "icon",
    },
    {
      url: "/favicon-16x16.png",
      type: "image/png",
      sizes: "16x16",
      rel: "icon",
    },
    {
      url: "/favicon.ico",
      type: "image/x-icon",
      sizes: "16x16",
      rel: "icon",
    },
  ],
  manifest: "/manifest.json",
  twitter: {
    images: {
      url: "/twitter-image.jpg",
      width: 1200,
      height: 630,
      alt: "ARESA App Logo - Real Estate Super App",
    },
    card: "summary_large_image",
    site: "@studioNM_co_kr",
    creator: "@studioNM_co_kr",
  },
  openGraph: {
    type: "website",
    locale: "ko_KR",
    url: "https://studio-nm.co.kr/",
    siteName: "아리사 - 부동산을 간편하고 안전하게",
    title: "ARESA",
    description: "부동산을 더 간편하고 더 안전하게 거래하도록 도와드립니다.",
    images: {
      url: "/openGraph-image.jpg",
      alt: "ARESA App Logo - Real Estate Super App",
      width: 1200,
      height: 630,
    },
  },
  other: {
    "theme-color": "#ffffff",
    "msapplication-TileColor": "#ffffff",
    "msapplication-TileImage": "/ms-icon-144x144.png",
    "msapplication-config": "/browserconfig.xml",
  },
  googleVerification: "xxx",
  naverVerification: "xxx",
};
